security:
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js|dhx)/
            security: false
        restricted_area:
            pattern:          ^/
            anonymous:        ~
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:
                path:           /logout
                target:         /
                invalidate_session: false
            remember_me:
                key: %secret%
                lifetime: 360000
                path: /

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    encoders:
        Gbs\LeaveBundle\Entity\User:
          algorithm: sha1
          iterations: 1
          encode_as_base64: false

    access_control:
        - { path: ^/login,          roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetPassword,          roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user,          roles: ROLE_LEAVES }
        - { path: ^/expense,          roles: ROLE_EXPENSE}
        - { path: ^/,               roles: IS_AUTHENTICATED_REMEMBERED }

    role_hierarchy:
        ROLE_COUNTRY_ADMIN: [ROLE_SONATA_COUNTRY_LIST, ROLE_SONATA_COUNTRY_VIEW, ROLE_SONATA_COUNTRY_CREATE, ROLE_SONATA_COUNTRY_EDIT, ROLE_SONATA_COUNTRY_DELETE, ROLE_SONATA_COUNTRY_EXPORT]
        ROLE_HOLIDAY_ADMIN: [ROLE_SONATA_HOLIDAY_LIST, ROLE_SONATA_HOLIDAY_VIEW, ROLE_SONATA_HOLIDAY_CREATE, ROLE_SONATA_HOLIDAY_EDIT, ROLE_SONATA_HOLIDAY_DELETE, ROLE_SONATA_HOLIDAY_EXPORT]
        ROLE_LEAVE_ADMIN: [ROLE_SONATA_LEAVE_LIST, ROLE_SONATA_LEAVE_VIEW, ROLE_SONATA_LEAVE_CREATE, ROLE_SONATA_LEAVE_EDIT, ROLE_SONATA_LEAVE_DELETE, ROLE_SONATA_LEAVE_EXPORT]
        ROLE_TR_ADMIN: [ROLE_SONATA_TR_LIST, ROLE_SONATA_TR_VIEW, ROLE_SONATA_TR_CREATE, ROLE_SONATA_TR_EDIT, ROLE_SONATA_TR_DELETE, ROLE_SONATA_TR_EXPORT]
        ROLE_EXPENSE_ADMIN: [ROLE_SONATA_EXPENSE_LIST, ROLE_SONATA_EXPENSE_VIEW, ROLE_SONATA_EXPENSE_CREATE, ROLE_SONATA_EXPENSE_EDIT, ROLE_SONATA_EXPENSE_DELETE, ROLE_SONATA_EXPENSE_EXPORT]
        ROLE_CATEGORY_ADMIN: [ROLE_SONATA_CATEGORY_LIST, ROLE_SONATA_CATEGORY_VIEW, ROLE_SONATA_CATEGORY_CREATE, ROLE_SONATA_CATEGORY_EDIT, ROLE_SONATA_CATEGORY_DELETE, ROLE_SONATA_CATEGORY_EXPORT]
        ROLE_FILE_ADMIN: [ROLE_SONATA_FILE_LIST, ROLE_SONATA_FILE_VIEW, ROLE_SONATA_FILE_CREATE, ROLE_SONATA_FILE_EDIT, ROLE_SONATA_FILE_DELETE, ROLE_SONATA_FILE_EXPORT]
        ROLE_DEPARTMENT_ADMIN: [ROLE_SONATA_DEPARTMENT_LIST, ROLE_SONATA_DEPARTMENT_VIEW, ROLE_SONATA_DEPARTMENT_CREATE, ROLE_SONATA_DEPARTMENT_EDIT, ROLE_SONATA_DEPARTMENT_DELETE, ROLE_SONATA_DEPARTMENT_EXPORT]
        ROLE_COMPANY_ADMIN: [ROLE_SONATA_COMPANY_LIST, ROLE_SONATA_COMPANY_VIEW, ROLE_SONATA_COMPANY_CREATE, ROLE_SONATA_COMPANY_EDIT, ROLE_SONATA_COMPANY_DELETE, ROLE_SONATA_COMPANY_EXPORT]
        ROLE_SITE_ADMIN: [ROLE_SONATA_SITE_LIST, ROLE_SONATA_SITE_VIEW, ROLE_SONATA_SITE_CREATE, ROLE_SONATA_SITE_EDIT, ROLE_SONATA_SITE_DELETE, ROLE_SONATA_SITE_EXPORT]
        ROLE_USER_ADMIN: [ROLE_SONATA_USER_LIST, ROLE_SONATA_USER_VIEW, ROLE_SONATA_USER_CREATE, ROLE_SONATA_USER_EDIT, ROLE_SONATA_USER_DELETE, ROLE_SONATA_USER_EXPORT]
        # roles to attribute
        ROLE_LEAVES: [ROLE_COUNTRY_ADMIN, ROLE_HOLIDAY_ADMIN, ROLE_LEAVE_ADMIN, ROLE_TR_ADMIN, ROLE_DEPARTMENT_ADMIN, ROLE_COMPANY_ADMIN, ROLE_SITE_ADMIN, ROLE_USER_ADMIN]
        ROLE_EXPENSE: [ROLE_EXPENSE_ADMIN, ROLE_CATEGORY_ADMIN, ROLE_FILE_ADMIN]
        ROLE_SUPERADMIN: [ROLE_USER_ADMIN]