<?php

namespace Gbs\LeaveBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PublicHolidayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublicHolidayRepository extends EntityRepository
{
}
