<?php

namespace Gbs\LeaveBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TrGivenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrGivenRepository extends EntityRepository
{
}
